Create how-to-vex.mc
spdx/using pull request #6
Opened 2024-07-30 16:55 UTC by zvr

copied over from https://github.com/spdx/spdx-spec/pull/933

2024-07-31 00:27 UTC, goneall commented
Note that this was approved in the tech call for the other repo.

@rnjudge - if you're good with this, I can merge.

2024-07-31 00:27 UTC, goneall approved these changes
LGTM

2024-08-12 00:56 UTC, bact requested changes

2024-08-12 00:56 UTC, bact commented on docs/how-to-vex.mc
> +  "externalRefs": [
```suggestion
  "externalRef": [
```
The property name has no trailing 's'.

2024-09-03 12:40 UTC, bact commented on docs/how-to-vex.mc
> +  "externalRefs": [
Altenatively, we can merge this PR as it is first then fix this in another PR.

2024-09-03 16:42 UTC, kestewart commented
@JPewdev - please review

2024-10-22 16:44 UTC, bact approved these changes

2024-10-22 16:44 UTC, merged